ETicaretWebApp/Controllers/CampgainsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ETicaretWebApp.Models;
using ETicaretWebApp.Models.Entities;

namespace ETicaretWebApp.Controllers
{
    public class CampgainsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Campgains
        public ActionResult Index()
        {
            return View(db.Campgains.ToList());
        }

        // GET: Campgains/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Campgain campgain = db.Campgains.Find(id);
            if (campgain == null)
            {
                return HttpNotFound();
            }
            return View(campgain);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ETicaretWebApp/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ETicaretWebApp.Models;
using ETicaretWebApp.Models.Entities;
using Microsoft.AspNet.Identity;

namespace ETicaretWebApp.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private string userId=string.Empty;
        public OrdersController()
        {
        }
        // GET: Orders
        public ActionResult Index()
        {
            userId = HttpContext.User.Identity.GetUserId();

            return View(db.Orders.Where(p=>p.OrderedById==userId).ToList());
        }

        // GET: Orders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null||order.OrderedById!= HttpContext.User.Identity.GetUserId())
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // GET: Orders/Create
        public ActionResult Create()
        {
            var list=db.Products.ToList();
            ViewBag.ProductList = new SelectList(db.Products.ToList().AsEnumerable(), "Id", "ProductName");
            return View();
        }

        // POST: Orders/Create
        // Aşırı gönderim saldırılarından korunmak için bağlamak istediğiniz belirli özellikleri etkinleştirin. 
        // Daha fazla bilgi için bkz. https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Address,Phone,Email")] Order order, int[] ProductIds)
        {
            userId = HttpContext.User.Identity.GetUserId();
            order.OrderedById = userId;
            order.CreatedById = userId;
            order.UpdatedDate = DateTime.Now;

            db.Orders.Add(order);
            db.SaveChanges();
            foreach (var productId in ProductIds)
            {
                var orderProduct = new OrderProduct
                {
                    OrderId = order.Id,
                    ProductId = productId
                };
                db.OrderProducts.Add(orderProduct);

                
            }
            db.SaveChanges();

            return RedirectToAction("Index");
        }

      

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ETicaretWebApp/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ETicaretWebApp.Models;
using ETicaretWebApp.Models.Entities;

namespace ETicaretWebApp.Controllers
{
    public class ProductsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Products
        public ActionResult Index()
        {
            var products = db.Products.Include(p => p.Category);
            return View(products.ToList());
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }    

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ETicaretWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ASP.NET Uygulamam</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Uygulama adı", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Gezintiyi aç/kapat" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Giriş", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Kampanyalar", "Index", "Campgains", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Siparişler", "Index", "Orders", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Ürünler", "Index", "Products", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Hakkında", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
                 @Html.Partial("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ASP.NET Uygulamam</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>